

[
  

  {
"_id": "64d3cc3a897e03bd3cd26f98",
"uniqueID": "3foice4Corte",
"name": "Foice",
"proficiency": "Arma Simples",
"proposite": "Corpo a Corpo",
"hilt": "Leve",
"price": 4,
"baseDamage": "1d6",
"criticalDamage": "x3",
"typeOfDamage": "Corte",
"reach": " - ",
"space": 1,
"description": "Originalmente um instrumento agrícola, consiste de uma lâmina curva presa a um cabo de madeira. Uma arma tradicional de druidas.",
"reference": "Livro Básico JDA",
"page": 0,
"operator": "obernac",
  },
  {
"_id": "64d3cd79897e03bd3cd26f9f",
"uniqueID": "4clava0Impacto",
"name": "Clava",
"proficiency": "Arma Simples",
"proposite": "Corpo a Corpo",
"hilt": "Uma Mão",
"price": 0,
"baseDamage": "1d6",
"criticalDamage": "x2",
"typeOfDamage": "Impacto",
"reach": " - ",
"space": 1,
"description": "Um pedaço de madeira empunhado como arma, geralmente usado por bárbaros ou criaturas brutais — ou como arma improvisada, como um galho de árvore ou pedaço de mobília. Sendo fácil de conseguir, seu preço é zero.",
"reference": "Livro Básico JDA",
"page": 0,
"operator": "obernac",
  },
  {
"_id": "64d3cfc08085081de4bbcba0",
"uniqueID": "5lança2Perfuração",
"name": "Lança",
"proficiency": "Arma Simples",
"proposite": "Corpo a Corpo",
"hilt": "Uma Mão",
"price": 2,
"baseDamage": "1d6",
"criticalDamage": "x2",
"typeOfDamage": "Perfuração",
"reach": "Curto",
"space": 1,
"description": "Qualquer arma feita com uma haste de madeira e uma ponta afiada, natural ou metálica. Por sua facilidade de fabricação, é muito comum entre orcs, kobolds, trogloditas e outras raças menos civilizadas. Uma lança pode ser arremessada.",
"reference": "Livro Básico JDA",
"page": 0,
"operator": "obernac",
  },
  {
"_id": "64d3d07c8085081de4bbcba7",
"uniqueID": "6maça12Impacto",
"name": "Maça",
"proficiency": "Arma Simples",
"proposite": "Corpo a Corpo",
"hilt": "Uma Mão",
"price": 12,
"baseDamage": "1d8",
"criticalDamage": "x2",
"typeOfDamage": "Impacto",
"reach": " - ",
"space": 1,
"description": "Bastão com um peso cheio de protuberâncias na ponta, a maça é usada por clérigos que fazem votos de não derramar sangue. De fato, um golpe de maça nem sempre derrama sangue, mas esmaga ossos.",
"reference": "Livro Básico JDA",
"page": 0,
"operator": "obernac",
  },
  {
"_id": "64d3d1e358dfdd47492b2cca",
"uniqueID": "7bordão0Impacto",
"name": "Bordão",
"proficiency": "Arma Simples",
"proposite": "Corpo a Corpo",
"hilt": "Duas Mãos",
"price": 0,
"baseDamage": "1d6/1d6",
"criticalDamage": "x2",
"typeOfDamage": "Impacto",
"reach": " - ",
"space": 2,
"description": "Um cajado apreciado por viajantes e camponeses por sua praticidade e fácil acesso (seu preço é zero). O bordão é uma arma dupla.",
"reference": "Livro Básico JDA",
"page": 0,
"operator": "obernac",
  },
  {
"_id": "64d3d282325bd7cae5a274a2",
"uniqueID": "8pique2Perfuração",
"name": "Pique",
"proficiency": "Arma Simples",
"proposite": "Corpo a Corpo",
"hilt": "Duas Mãos",
"price": 2,
"baseDamage": "1d8",
"criticalDamage": "x2",
"typeOfDamage": "Perfuração",
"reach": " - ",
"space": 2,
"description": "Essencialmente uma lança muito longa. O pique é uma arma alongada.",
"reference": "Livro Básico JDA",
"page": 0,
"operator": "obernac",
  },
  {
"_id": "64d3d3d853648fb146214fd1",
"uniqueID": "9tacape0Impacto",
"name": "Tacape",
"proficiency": "Arma Simples",
"proposite": "Corpo a Corpo",
"hilt": "Duas Mãos",
"price": 0,
"baseDamage": "1d10",
"criticalDamage": "x2",
"typeOfDamage": "Impacto",
"reach": " - ",
"space": 2,
"description": "Versão maior e/ou com pregos de uma clava. Usado por bárbaros e humanoides bestiais, não é uma arma elegante, mas faz o serviço.",
"reference": "Livro Básico JDA",
"page": 0,
"operator": "obernac",
  },
  {
"_id": "64da92c8c0b28c5726337771",
"uniqueID": "10azagaia1Perfuração",
"name": "Azagaia",
"proficiency": "Arma Simples",
"proposite": "Arremesso",
"hilt": "Uma Mão",
"price": 1,
"baseDamage": "1d6",
"criticalDamage": "x2",
"typeOfDamage": "Perfuração",
"reach": "Medio",
"space": 1,
"description": "Uma lança leve e flexível, própria para arremesso. Pode ser usada como arma corpo a corpo, mas você sofre uma penalidade de –5 no teste de ataque.",
"reference": "Livro Básico JDA",
"page": 0,

"operator": "obernac",
  }
]