[
  {
    _id: "64d3c8c67f01b4cc29dbd4f7",
    uniqueID: "1adaga2Perfuração",
    name: "Adaga",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Leve",
    price: 2,
    baseDemage: "1d4",
    critcalDamege: "19",
    typeOfDamege: "Perfuração",
    reach: "Curto",
    space: 1,
    description:
      "Esta faca afiada é usada por muitos habitantes adultos do Reinado, embora seja favorita de ladrões e assassinos, por ser facilmente escondida\n(fornece +5 em testes de Ladinagem para ocultá-la). \nQuando ataca com uma adaga, você pode usar sua Destreza em vez de Força nos testes de ataque. Uma adaga pode ser arremessada.",
    reference: "Livro Básico JDA",
    sequence: 1,
    operator: "obernac",
    createdAt: "2023-08-09T17:11:34.783Z",
    updatedAt: "2023-08-09T17:11:34.783Z",
    __v: 0,
  },
  {
    _id: "64d3ca996273f4e751d9c4d7",
    uniqueID: "2espadacurta10Perfuração",
    name: "Espada curta",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Leve",
    price: 10,
    baseDemage: "1d6",
    critcalDamege: "19",
    typeOfDamege: "Perfuração",
    reach: " - ",
    space: 1,
    description:
      "O tipo mais comum de espada, usada por guardas ou como arma secundária de guerreiros mais capazes. Mede entre 40 e 50cm",
    reference: "Livro Básico JDA",
    sequence: 2,
    operator: "obernac",
    createdAt: "2023-08-09T17:19:21.877Z",
    updatedAt: "2023-08-09T17:19:21.877Z",
    __v: 0,
  },
  {
    _id: "64d3cc3a897e03bd3cd26f98",
    uniqueID: "3foice4Corte",
    name: "Foice",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Leve",
    price: 4,
    baseDemage: "1d6",
    critcalDamege: "x3",
    typeOfDamege: "Corte",
    reach: " - ",
    space: 1,
    description:
      "Originalmente um instrumento agrícola, consiste de uma lâmina curva presa a um cabo de madeira. Uma arma tradicional de druidas.",
    reference: "Livro Básico JDA",
    sequence: 3,
    operator: "obernac",
    createdAt: "2023-08-09T17:26:18.659Z",
    updatedAt: "2023-08-09T17:26:18.659Z",
    __v: 0,
  },
  {
    _id: "64d3cd79897e03bd3cd26f9f",
    uniqueID: "4clava0Impacto",
    name: "Clava",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Uma Mão",
    price: 0,
    baseDemage: "1d6",
    critcalDamege: "x2",
    typeOfDamege: "Impacto",
    reach: " - ",
    space: 1,
    description:
      "Um pedaço de madeira empunhado como arma, geralmente usado por bárbaros ou criaturas brutais — ou como arma improvisada, como um galho de árvore ou pedaço de mobília. Sendo fácil de conseguir, seu preço é zero.",
    reference: "Livro Básico JDA",
    sequence: 4,
    operator: "obernac",
    createdAt: "2023-08-09T17:31:37.925Z",
    updatedAt: "2023-08-09T17:31:37.925Z",
    __v: 0,
  },
  {
    _id: "64d3cfc08085081de4bbcba0",
    uniqueID: "5lança2Perfuração",
    name: "Lança",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Uma Mão",
    price: 2,
    baseDemage: "1d6",
    critcalDamege: "x2",
    typeOfDamege: "Perfuração",
    reach: "Curto",
    space: 1,
    description:
      "Qualquer arma feita com uma haste de madeira e uma ponta afiada, natural ou metálica. Por sua facilidade de fabricação, é muito comum entre orcs, kobolds, trogloditas e outras raças menos civilizadas. Uma lança pode ser arremessada.",
    reference: "Livro Básico JDA",
    sequence: 5,
    operator: "obernac",
    createdAt: "2023-08-09T17:41:20.479Z",
    updatedAt: "2023-08-09T17:41:20.479Z",
    __v: 0,
  },
  {
    _id: "64d3d07c8085081de4bbcba7",
    uniqueID: "6maça12Impacto",
    name: "Maça",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Uma Mão",
    price: 12,
    baseDemage: "1d8",
    critcalDamege: "x2",
    typeOfDamege: "Impacto",
    reach: " - ",
    space: 1,
    description:
      "Bastão com um peso cheio de protuberâncias na ponta, a maça é usada por clérigos que fazem votos de não derramar sangue. De fato, um golpe de maça nem sempre derrama sangue, mas esmaga ossos.",
    reference: "Livro Básico JDA",
    sequence: 6,
    operator: "obernac",
    createdAt: "2023-08-09T17:44:28.317Z",
    updatedAt: "2023-08-09T17:44:28.317Z",
    __v: 0,
  },
  {
    _id: "64d3d1e358dfdd47492b2cca",
    uniqueID: "7bordão0Impacto",
    name: "Bordão",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Duas Mãos",
    price: 0,
    baseDemage: "1d6/1d6",
    critcalDamege: "x2",
    typeOfDamege: "Impacto",
    reach: " - ",
    space: 2,
    description:
      "Um cajado apreciado por viajantes e camponeses por sua praticidade e fácil acesso (seu preço é zero). O bordão é uma arma dupla.",
    reference: "Livro Básico JDA",
    sequence: 7,
    operator: "obernac",
    createdAt: "2023-08-09T17:50:27.633Z",
    updatedAt: "2023-08-09T17:50:27.633Z",
    __v: 0,
  },
  {
    _id: "64d3d282325bd7cae5a274a2",
    uniqueID: "8pique2Perfuração",
    name: "Pique",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Duas Mãos",
    price: 2,
    baseDemage: "1d8",
    critcalDamege: "x2",
    typeOfDamege: "Perfuração",
    reach: " - ",
    space: 2,
    description:
      "Essencialmente uma lança muito longa. O pique é uma arma alongada.",
    reference: "Livro Básico JDA",
    sequence: 8,
    operator: "obernac",
    createdAt: "2023-08-09T17:53:06.115Z",
    updatedAt: "2023-08-09T17:53:06.115Z",
    __v: 0,
  },
  {
    _id: "64d3d3d853648fb146214fd1",
    uniqueID: "9tacape0Impacto",
    name: "Tacape",
    proficience: "Arma Simples",
    proposite: "Corpo a Corpo",
    hilt: "Duas Mãos",
    price: 0,
    baseDemage: "1d10",
    critcalDamege: "x2",
    typeOfDamege: "Impacto",
    reach: " - ",
    space: 2,
    description:
      "Versão maior e/ou com pregos de uma clava. Usado por bárbaros e humanoides bestiais, não é uma arma elegante, mas faz o serviço.",
    reference: "Livro Básico JDA",
    sequence: 9,
    operator: "obernac",
    createdAt: "2023-08-09T17:58:48.174Z",
    updatedAt: "2023-08-09T17:58:48.174Z",
    __v: 0,
  },
  {
    _id: "64da92c8c0b28c5726337771",
    uniqueID: "10azagaia1Perfuração",
    name: "Azagaia",
    proficience: "Arma Simples",
    proposite: "Arremesso",
    hilt: "Uma Mão",
    price: 1,
    baseDemage: "1d6",
    critcalDamege: "x2",
    typeOfDamege: "Perfuração",
    reach: "Medio",
    space: 1,
    description:
      "Uma lança leve e flexível, própria para arremesso. Pode ser usada como arma corpo a corpo, mas você sofre uma penalidade de –5 no teste de ataque.",
    reference: "Livro Básico JDA",
    sequence: 10,
    operator: "obernac",
    createdAt: "2023-08-14T20:47:04.772Z",
    updatedAt: "2023-08-14T20:47:04.772Z",
    __v: 0,
  },
];
